openapi: "3.0.0"
info:
  title: My API
  version: "1.0.0"
  description: This API provides a simple "Hello, world!" message.

paths:
  /hello:
    get:
      summary: Retrieve a greeting message
      responses:
        '200':
          description: A successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Hello, world!
    post:
      summary: Create a new greeting message
      parameters:
        - in: query
          name: name
          schema:
            type: string
      # requestBody:
      #   required: true
      #   content:
      #     application/json:
      #       schema:
      #         type: object
      #         properties:
      #           name:
      #             type: string
      responses:
        '201':
          description: Greeting message created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Greeting message created
